name: Publish Docker image
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  page_build:
  release:
    types: 
      - created
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          path: backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: endocker299/pipelines
          tag_with_ref: true
